### ISSUE TITLE
Security Mode Issue

### ISSUE THREAD

**Issue by matthieudolci** [insentia/windows_sql#6]
Hello,

We are having issues with the security mode.
We want to use windows-only instead of SQL, but when we dont supply any value to get windows-only, we always end-up with this error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Security mode only support SQL value, if no value is supplied, then Windows-Only authentication mode is used at /etc/puppet/environments/production/modules/windows_sql/manifests/params.pp:151

Is there anything we are missing?

Thanks

**Comment by ninja-2** [comment]
Hello, 

Sorry for the delay.
By lookink back in my code, I think this action should not be this one. You can replace it by a notice function or just comment the line #151 in manifests/params.pp file.

Let me know if it work.
I will fix this in the next release if it works

Have a nice evening.
